name: Sync fork

on:
  schedule:
    - cron: '0 0 * * *'  # This will run the job every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v3
        with:
          repository: N-SDM/N-SDM
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/antadde/N-SDM.git
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories
          git push origin main
